apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: devops-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: devops-worker:test
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - "import os; os.path.exists('/tmp')"
            initialDelaySeconds: 10
            periodSeconds: 30
